"""

Revision ID: 07ba6f5a7f6c
Revises: 3d1284d316b9
Create Date: 2021-04-21 19:25:54.086686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07ba6f5a7f6c'
down_revision = '3d1284d316b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'photos', 'events', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.drop_column('photos', 'parent_id')
    # ### end Alembic commands ###
