"""

Revision ID: 1e208eb360bd
Revises: 07ba6f5a7f6c
Create Date: 2021-04-22 17:40:29.400823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e208eb360bd'
down_revision = '07ba6f5a7f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
