"""empty message

Revision ID: 3d1284d316b9
Revises: 968f5b838483
Create Date: 2021-04-21 19:22:04.550776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d1284d316b9'
down_revision = '968f5b838483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'event')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('event', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
